### ISSUE TITLE
Missing proxy_ssl_name Statement

### ISSUE THREAD

**Issue by simongregorebner** [hauntsaninja/nginx_pypi_cache#2]
There is a missing proxy_ssl_name statement just below this line:
https://github.com/hauntsaninja/nginx_pypi_cache/blob/543405b16b8135fbcaecac5ff2181e93f9d3311c/nginx.conf#L92

without adding a 
```
proxy_ssl_name pypi.org;
```
just after the config will not work (at least not in a docker container)

**Comment by hauntsaninja** [comment]
Thanks, fixed in https://github.com/hauntsaninja/nginx_pypi_cache/pull/3

For whatever reason, it still works fine for me (but I also remember initially I didn't set `proxy_ssl_name` at all and it only broke when upstream changed something). Does running `bash tests/mitmtest.sh` work for you?

**Comment by simongregorebner** [comment]
without the `proxy_ssl_name` statement the test didn't succeed, with it works. Thanks for fixing!
