### ISSUE TITLE
keep use_temp_path=off?

### ISSUE THREAD

**Issue by pkking** [hauntsaninja/nginx_pypi_cache#9]
As [nginx doc](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache) mentioned, temp file and cache file should better live in the same filesystem, in the example `nginx.conf`, most of the users will mount another filesystem into the cache dir directly (say: `/var/lib/nginx/pypi`) which cause the `rename` be more expensive :P

**Comment by hauntsaninja** [comment]
Yeah, good idea. I think this got added to our internal fork at work too :-)
